# dtypes.py: dictionary of dictionaries to be included in each file to specify the dtype of each dataset
# necessary because compiler complained when reading csv from local folder 'data'.

dtypes = {
    'games_details': {
        'GAME_ID': int,
        'TEAM_ID': int,
        'TEAM_ABBREVIATION': str,
        'TEAM_CITY': str,
        'PLAYER_ID': int,
        'PLAYER_NAME': str,
        'NICKNAME': str,
        'START_POSITION': str,
        'COMMENT': str,
        'MIN': str,  # You may want to handle this as time or float after cleaning
        'FGM': float,
        'FGA': float,
        'FG_PCT': float,
        'FG3M': float,
        'FG3A': float,
        'FG3_PCT': float,
        'FTM': float,
        'FTA': float,
        'FT_PCT': float,
        'OREB': float,
        'DREB': float,
        'REB': float,
        'AST': float,
        'STL': float,
        'BLK': float,
        'TO': float,
        'PF': float,
        'PTS': float,
        'PLUS_MINUS': float,
    },
    'games': {
        'GAME_DATE_EST': str,
        'GAME_ID': int,
        'GAME_STATUS_TEXT': str,
        'HOME_TEAM_ID': int,
        'VISITOR_TEAM_ID': int,
        'SEASON': int,
        'TEAM_ID_home': int,
        'PTS_home': float,
        'FG_PCT_home': float,
        'FT_PCT_home': float,
        'FG3_PCT_home': float,
        'AST_home': float,
        'REB_home': float,
        'TEAM_ID_away': int,
        'PTS_away': float,
        'FG_PCT_away': float,
        'FT_PCT_away': float,
        'FG3_PCT_away': float,
        'AST_away': float,
        'REB_away': float,
        'HOME_TEAM_WINS': int,
    },
    'players': {
        'PLAYER_NAME': str,
        'TEAM_ID': int,
        'PLAYER_ID': int,
        'SEASON': int,
    },
    'rankings': {
        'TEAM_ID': int,
        'LEAGUE_ID': int,
        'SEASON_ID': int,
        'STANDINGSDATE': str,
        'CONFERENCE': str,
        'TEAM': str,
        'G': int,
        'W': int,
        'L': int,
        'W_PCT': float,
        'HOME_RECORD': str,
        'ROAD_RECORD': str,
        'RETURNTOPLAY': float,
    },
    'teams': {
        'LEAGUE_ID': int,
        'TEAM_ID': int,
        'MIN_YEAR': int,
        'MAX_YEAR': int,
        'ABBREVIATION': str,
        'NICKNAME': str,
        'YEARFOUNDED': int,
        'CITY': str,
        'ARENA': str,
        'ARENACAPACITY': float,
        'OWNER': str,
        'GENERALMANAGER': str,
        'HEADCOACH': str,
        'DLEAGUEAFFILIATION': str,
    },
}
